# Generated by Django 5.2.11 on 2026-06-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutchieWriteAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=120)),
                ('action', models.CharField(max_length=40)),
                ('acct_id', models.BigIntegerField(blank=True, null=True)),
                ('shipment_id', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(max_length=500)),
                ('ok', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dutchie_acct_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('mjstateidno', models.CharField(blank=True, max_length=120)),
                ('over_21', models.BooleanField(null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=40)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('raw_scan', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone'], name='customers_c_phone_8493fa_idx'), models.Index(fields=['dutchie_acct_id'], name='customers_c_dutchie_a77c1a_idx')],
            },
        ),
    ]
