# Generated by Django 5.2.11 on 2026-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(db_index=True, max_length=120)),
                ('product_id', models.BigIntegerField(db_index=True, null=True)),
                ('batch_id', models.BigIntegerField(null=True)),
                ('serial_no', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('price', models.FloatField(default=0)),
                ('available', models.FloatField(default=0)),
                ('cannabis', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['store', 'name'], name='budtender_i_store_b229b6_idx'), models.Index(fields=['store', 'product_id'], name='budtender_i_store_84a28b_idx')],
            },
        ),
    ]
